on: push
name: deploy
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: install
      run: npm install
    - name: build
      run: npm run build
    - uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: build/*, Dockerfile
        target: ${{ secrets.WORKDIR }}/landing
    - uses: convictional/trigger-workflow-and-wait@v1.6.1
      with:
        owner: otakos-con-katanas/
        repo: mono
        github_token: ${{GH_TOKEN}}
        workflow_file_name: run.yaml

        
